### PR TITLE
Introduce new 'show_on_hub' property to IR

### PR DESCRIPTION
**Pull request by iwootten**
### PR Context

For NISRA's Census we need to be able to disable the individual response showing on the hub. This PR is to introduce a new property to support this in runner along with a valid example schema of individual response.

### CODE REVIEW

**Comment by iwootten** [comment]
[NI - remove IR link displayed from the hub (M)](https://trello.com/c/X3dILIul/4162-ni-remove-ir-link-displayed-from-the-hub-m)

**Review by berroar — APPROVED** [review]

**Review by MebinAbraham — APPROVED** [review]
We really need a way to share schemas.

**Comment by iwootten** [comment]
> We really need a way to share schemas.

I mentioned this when working on my last PR. The entire valid folder ends up getting tested multiple times.

**Comment by iwootten** [comment]
For NISRA's Census we need to be able to disable the individual response showing on the hub

**Pull request merged**
